accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from accounts.forms import UserLoginForm
from accounts.views import RegisterView,edit_profile


urlpatterns = [
    path('login/', LoginView.as_view(authentication_form=UserLoginForm), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('profile/', edit_profile, name="profile"),
    path('', include('django.contrib.auth.urls'))
]

projects/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.ProjectListView.as_view(), name="Project_list"),
    path('project/create', views.ProjectCreatView.as_view(), name="Project_create"),
    path('project/edit/<int:pk>', views.ProjectUpdateView.as_view(), name="Project_update"),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name="Project_delete"),
    path('task/create', views.TaskCreateView.as_view(), name="Task_create"),
    path('task/edit/<int:pk>', views.TaskUpdateView.as_view(), name="Task_update"),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name="Task_delete"),
]

projects_management/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')), 
    path('', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ProjectStatus(models.IntegerChoices):
    PANDING = 1, 'Panding'
    COMPLETED = 2, 'Completed'
    POSTPONED = 3, 'Postponed'
    CANCELED = 4, 'Canceled'


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.IntegerField(
        choices = ProjectStatus.choices,
        default = ProjectStatus.PANDING
    )
    created_at = models.DateField(auto_now_add = True)
    updated_at = models.DateField(auto_now = True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT) 
    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null = True
    )

    def __str__(self):
        return self.description 


class Task(models.Model):
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User


attrs = {"class": 'form-control'}

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)


    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs=attrs)
    )
    
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs=attrs)
    )


class UserRegisterForm(UserCreationForm):
    firsr_name = forms.CharField(
        label='First Name',
        widget=forms.TextInput(attrs=attrs)
    )
    last_name = forms.CharField(
        label='Last Name',
        widget=forms.TextInput(attrs=attrs)
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput (attrs=attrs)
    )
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs=attrs)
    )
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs=attrs)
    )
    password2 = forms.CharField(
        label='Password Confirmation',
        strip=False,
        widget=forms.PasswordInput(attrs=attrs)
    )

    class Meta(UserCreationForm.Meta):
        fields = ('first_name', 'last_name', 'Username', 'email')



class ProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs=attrs),
            'last_name': forms.TextInput(attrs=attrs),
            'email': forms.EmailInput(attrs=attrs)
        }

projects/forms.py
from django import forms
from . import models

attrs = {'class':'form-control'}

class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'description']
        widgets = {
            'category' : forms.Select(attrs=attrs),
            'title' : forms.TextInput(attrs=attrs),
            'description' : forms.Textarea(attrs=attrs)
        }

class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'status']
        widgets = {
            'category' : forms.Select(attrs=attrs),
            'title' : forms.TextInput(attrs=attrs),
            'status' : forms.Select(attrs=attrs)
        }
        

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from accounts.forms import UserRegisterForm, ProfileForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

# Create your views here.
class RegisterView(CreateView):
    form_class = UserRegisterForm
    # success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

    def get_success_url(self):
        login(self.request, self.object)
        return reverse_lazy('Project_list')

@login_required
def edit_profile(request):
    if request.method == "POST":
        form = ProfileForm(request.POST,isinstance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(isinstance=request.user)
        return render(request,'profile.html', {
            "form": form
        })

projects/views.py
from django.views.generic import ListView, CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy, reverse
from . import models
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
   
class ProjectListView(LoginRequiredMixin, ListView):
    model = models.Project
    template_name = 'project/list.html'
    paginate_by = 6

    # def get_queryset(self):
    #     query_set = super().get_queryset()
    #     where = {}
    #     q = self.request.GET.get('q', None)
    #     if q:
    #         where['title-icontains'] = q
    #     return query_set.filter(**where)


class ProjectCreatView(LoginRequiredMixin, CreateView):
    model = models.Project
    form_class = forms.ProjectCreateForm
    template_name = 'project/create.html'
    success_url = reverse_lazy("Project_list")


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Project
    form_class = forms.ProjectUpdateForm
    template_name = 'project/update.html'
    
    def get_success_url(self):
        return reverse('Project_update', args=[self.object.id])


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Project
    template_name = 'project/delete.html'
    success_url = reverse_lazy('Project_list')
     

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = models.Task
    fields = ['project', 'description']
    http_method_names = ['post']

    def get_success_url(self):
        return reverse('Project_update', args=[self.object.project.id])


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Task
    fields = ['is_completed']
    http_method_names = ['post']

    def get_success_url(self):
        return reverse('Project_update', args=[self.object.project.id])


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Task
    
    def get_success_url(self):
        return reverse('Project_update', args=[self.object.project.id])
     

projects/templates/base.html
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <title>Django Project Management</title>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
            crossorigin="anonymous"
        >
        <link 
            rel="stylesheet" 
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
        >
    </head>
    <body class="d-flex flex-column h-100 bg-light">
        {% include "partials/header.html" %}
        <main class="flex-shrink-0">
            <div class="container mt-5">
                {% block content %}
        
                {% endblock %}
            </div>
        </main>
        {% include "partials/footer.html" %}
        <script 
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
            crossorigin="anonymous">
        </script>
    </body>
</html>

projects/templates/common/form.html
{% load i18n %}
<ul>
    {% for error in form.non_field_errors %}
      <li class="list-group-item list-group-item-danger">{{ error|escape }}</li>
    {% endfor %}
    {% for field in form %}
        {% for error in form.non_field_errors %}
            <li class="list-group-item list-group-item-danger">{{ error|escape }}</li>
        {% endfor %}
    {% endfor %}
</ul>
{% for field in form %}
    <div class="mb-3">
        <label class="form-label">{{ field.label }}</label>
        {{ field }}
    </div>
{% endfor %}

projects/templates/partials/footer.html
{% load i18n %}
<footer class="footer mt-auto py-3 bg-white border">
    <dir class="container">
        <span class="text-muted">
            {% trans "(c) 2022 Programer all rights reseved." %}
        </span>
    </dir>
</footer>

projects/templates/partials/header.html
{% load i18n %}
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success bg-gradient p-3">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Project_list'  %}">{% trans "Projects Managment" %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Project_list' %}">{% trans "HOME" %}</a>
          </li>
        </ul>
        {% if user.is_authenticated  %}
        <ul class="navbar-nav mb-2 mb-lg-0 me-3">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.usernmae }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'profile'%}">{% trans "Profile" %}</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout'%}">{% trans "Logout" %}</a></li>
            </ul>
        </ul>
          <form method="GET" action="{% url 'Project_list'%}" class="d-flex">
            <div class="input-group">
              <input 
                type="text"
                name="q"
                class="form-control"
                placeholder="{% trans 'Search' %}"
                value="{{ request.GET.q }}"
              >
              <button class="btn btn-outline-light" type="submit">
                <i class="bi bi-search"></i>
              </button>
            </div>
          </form>
        {% else %}
          <a class="btn btn-outline-light mx" href="{% url 'register' %}">
            {% trans "Register" %}
          </a>
          <a class="btn btn-outline-light" href="{% url 'login' %}">
            {% trans "Login" %}
          </a>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

projects/templates/project/create.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="card col-md-6 px-0">
                <div class="card-header">
                    <h3 class="mb-0 py-2">
                        {% trans "New Project" %}
                    </h3>
                </div>
                <div class="card-body">
                    <form action="POST">
                        {% csrf_token %}
                        {% include "common/form.html" with form=form %}
                        <button class='btn btn-success'>
                            {% translate "Create" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock  %}

projects/templates/project/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h2>{% trans "Alert" %}</h2>
    <form method="post">
        {% csrf_token %}
        <p class="text-muted my-4">
            {% trans "Are you sure to delete" %} {{ project.title }}
        </p>
        <input 
            class="btn btn-danger" 
            type="submit" 
            value="{% trans 'Delete' %}"
        >
    </form>
{% endblock  %}

projects/templates/project/list.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}

    <div class="d-flex">
        <h3 class="me-auto">{% trans "My Project" %}</h3>
            <div>
                <a 
                    class="btn btn-outline-success" 
                    href="Project_create">
                <i class="bi bi-plus-lg"></i>{% trans "New Project" %}
                </a>
            </div>
    </div>

    <div class="row my-5">
        {% for project in object_list %}
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <p>
                            <span class="badge rounded-pill bg-dark">
                                {{ project.get_status_display }}
                            </span>
                        </p>
                        <h3 class="card-title fs-6">{{ project.title }}</h3>
                        <p class="card-text text-muted small">{{ project.description }}</p>
                        <div class="d-flex">
                            <span class="card-text text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{ project.created_at }}">
                                    {{ project.created_at }}
                                </time>
                            </span>
                            <a href="{% url 'Project_update' project.id %}" class="btn btn-sm btn-outline mx-1">
                                {% trans "Edit" %}
                            </a>
                            <a href="{% url 'Project_delete' project.id %}" class="btn btn-sm btn-outline-danger">
                                <i class="bi bi-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>  
            </div>
        {% empty %}
            <div class="h-100 bh-white border rounded-3 text-center">
                <p>{% trans "THere are no projects to shoW" %}</p>
                <p>
                    <i class="bi bi-emoji-frown fs-1"></i>
                </p>
                <a 
                    class="btn btn-success" 
                    href="Project_create">
                <i class="bi bi-plus-lg"></i>{% trans "New Project" %}
                </a>
            </div>
        {% endfor %}
        {% if page_obj.paginatou.count > 0 %}
            <div class="d-flex justify-content-center bd-highlighit mb-3">
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    {% trans "Previous" %}
                                </a>
                            </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                {% trans "Previous" %}
                            </a>
                        </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a 
                                    class="page-link" 
                                    href="?page={{ page_obj.next_page_number }}"
                                >
                                    {% trans "Next" %}
                                </a>
                            </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                {% trans "Next" %}
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>
    
{% endblock  %}

projects/templates/project/task.html
{% load i18n %}

<ul class="list-group">
    {% for task in project.task_set.all %}
        <li class="list-group-item d-flex">
            <form method="post" action="{% url 'Task_update' task.id %}" class="my-auto me-2">
                {% csrf_token %}
                <input
                    class="form-check-input"
                    type="checkbox"  
                    name="is_completed"
                    {% if task.is_completed %} checked {% endif %}
                    onchange="this.form.submit()"
                /> 
            </form>
            <p class="my-auto me-auto">
                {{ task.description }}
            </p>
            <form method="post" action="{% url 'Task_create' %}">
                {% csrf_token %}
                <button type="submit" class="btn">
                    <i class="bi bi-trash text-danger"></i>
                </button>
            </form>            
        </li>       
    {% endfor %}
</ul>

<div class="card mt-2">
    <form method="post" action="{% url 'Task_create' %}" class="d-flex">
        {% csrf_token %}
        <div class="input-gorup">
            <input type="hidden" value="{{ project.id }}" name="project">
            <input type="text" name="description" class="form-control" placeholder="{% trans 'New Task' %}" required/>
            <input type="submit" class="btn btn-outline-dark" value="{% trans 'Add' %}"/>
        </div>
    </form>
    
</div>

projects/templates/project/update.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    
    <nav aria-label="breadcrumb">
        <ol class='breadcrumb'>
            <li class="breadcrumb-item active" aria-current="page">
                <h5>
                    {{ object.title }}
                </h5>
            </li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-3">
            <form action="POST">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="d-flex mt-2">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{ object.create_at }}">
                                    {{ object.created_at   }}
                            </span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="d-grid gap-2">
                            <button class="btn btn-success">
                                <i class="bi bi-save"></i>
                                {% trans "Save" %}
                            </button>
                            <button class="btn btn-danger">
                                <i class="bi bi-trash"></i>
                                {% trans "Delete" %}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-9">
            {% include "project/task.html" with project=object %}
        </div>
    </div>
{% endblock  %}